sudo: required
services:
    - docker

before_install:
    - docker build -t mskanyal/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t mskanyal/mutli-client ./client
    - docker build -t mskanyal/mutli-nginx ./nginx
    - docker build -t mskanyal/mutli-server ./server
    - docker build -t mskanyal/mutli-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push mskanyal/mulit-client
    - docker push mskanyal/multi-nginx
    - docker push mskanyal/multi-server
    - docker push mskanyal/multi-worker
